### ISSUE TITLE
Would love to contribute...

### ISSUE THREAD

**Issue by gisdev-km** [goanpeca/pyras#1]
Just curious if you have gotten started on this and would love to contribute where I can.

**Comment by goanpeca** [comment]
Hey @glsdev-km, great to hear that more and more people are interested in this, that would make 3 now hahaha (including myself!)

The thing is that so far I have been not wrapping a dll..(there i no such thing with hecras) but using PyWin32 to wrap the hecras controller (through the COM interface). I have asked someone to find if the USACE would be willing to share source code for the numerical engine (which is actually written in FORTRAN as far as I know...). My bet is that they wont, but I at least asked if they could share precompiled *.dll (for windows) and *.so (for unix) cause at this stage this package would only work on Windows...

I really do not like how the hec ras controller functions work, so I want to make this module as pythonic as I can, which requires making an abstraction of a river model, so we could start some work on that.

Thanks for the interest

**Comment by gisdev-km** [comment]
Yeah, finding out the same.  Looks like we've come to the same conclusion separately regarding the controller functions and trying to get them to interact with ctypes and PyWin32.

Being here in Sacramento, I'll ask a contact RE: the precompiled .dll files to see if we can accelerate the process.

**Comment by goanpeca** [comment]
Great, thanks for that, lets see if we get any news soon

Cheers

**Comment by gisdev-km** [comment]
My contact heard back... Essentially said they are only focusing on 2D and GIS Tools in the short term.  Next year they plan to overhaul the interface and may revisit the subject of accessing it from other languages.  As of right now, it's strictly VB from the programming end.

**Comment by goanpeca** [comment]
Hi again, thanks for the heads up, still if you are still interested we can work on this package using the ras controller through the com interface (that is what I do now) and eventually it would be (in theory) an easy switch to wrap the engine..., unless of course the engine functions are completely different to the ones available in the controller.

I have barely any code written at this point, but I can start pushing what I do in the coming weeks

**Comment by gisdev-km** [comment]
Definitely.  Go ahead and push up what you get done and I'll go from there.  Currently doing everything in VB and would love to swap it out.

**Comment by goanpeca** [comment]
Question

`RASPy` vs `PyRAS`? (module names....`raspy` vs `pyras`)

**Comment by gisdev-km** [comment]
PyRAS as RasPy sounds like it could be a raspberry pi project. Thoughts?

**Comment by goanpeca** [comment]
Haha, I thought exactly the same!, PyRAS it is.

I already uploaded some stuff I had... basically a thin wrapper of the pywin32 wrapper. 

Using 4.1

**Comment by goanpeca** [comment]
Feel free to jump in whenever you want ;-)

https://pypi.python.org/pypi/PyRAS

**Comment by goanpeca** [comment]
So after some weekend coding, I have mapped almost every method from `HECRASController` and `HECRASGeometry` and have (preliminary) support for RAS500 (on top of RAS41).

Now making an example and test for each and every function... (lengthy process...!) to make sure everything works, plus adding some input and exception handling and 0-based vs 1-based array issues.

Install does not work from pip, so better to use git clone for the moment...
