### ISSUE TITLE
PyRAS not found via PIP

### ISSUE THREAD

**Issue by gisdev-km** [goanpeca/pyras#2]
Looks like there is an issue with PyRAS not showing up via PIP

![screen shot 2015-04-06 at 8 07 03 am](https://cloud.githubusercontent.com/assets/2168316/7006198/15e5d8ee-dc34-11e4-82b4-27a30f6a95a1.png)

**Comment by goanpeca** [comment]
No issue at all.. I have not yet uploaded a package... was waiting to have a minimum stable version.

Maybe is better for the moment if you just clone from git, this week should see the first beta release if everything goes well.

**Comment by goanpeca** [comment]
I am  also thinking of moving this repo to an organization and bundle there any other tool that pops in the river modelling domain

**Comment by gisdev-km** [comment]
I haven't had much experience with GH Organizations to know if that is a positive or negative move.  It makes sense to bundle everything together as a collection of tools but am not familiar with the software to know if that's a smarter move.

**Comment by goanpeca** [comment]
It depends I guess.. so far PyRAS is a windows tied thing... but some of the other components will not necessarily be tied to windows, so it makes sense to have them as separate modules... but it is not a big deal right now anyway.

**Comment by gisdev-km** [comment]
Looks like i have 4.2 Beta installed. Getting a copy of 5 from the modelers to test as it looks like 4.2 doesn't register any variables that os.environ picks up.

**Comment by goanpeca** [comment]
I am only using 4.1 and 5.0.0 beta

**Comment by gisdev-km** [comment]
Correct.  Seeing that in the setup.py.  Getting my end compliant for testing.

**Comment by goanpeca** [comment]
Actually I have not tried to install... so ... would not know :p, using directly from source, maybe you can do this in the mean time, I will only move to installer as soon as coverage is complete (getting there)

**Comment by goanpeca** [comment]
Ok, sorry there were some issues with the setup.py

It should install now correctly. Take a look at the `examples.py` file, that is where (for now) I am testing each and every method.

**Comment by gisdev-km** [comment]
No, meant I was installing HEC-RAS 5.0 to be on the same version for you.  It was throwing an error with 4.2 not having "HEC-RAS" installed at all.

5.0 fixed the issue and 'python example.py' now works (after uncommenting rc = pyras.HECRASController('RAS500')).

**Comment by goanpeca** [comment]
Great :+1: , first steps!

**Comment by gisdev-km** [comment]
Interesting that commenting out rc.ShowRAS() still displays the HEC-RAS window unlike VB's HECRASController.  Need to dig into your code and see what's up.

**Comment by gisdev-km** [comment]
Definitely :thumbsup:

![screen shot 2015-04-06 at 8 57 04 am](https://cloud.githubusercontent.com/assets/2168316/7007034/eaa1b1a6-dc3a-11e4-8323-42ef7d6785f1.png)

**Comment by goanpeca** [comment]
Gotta go now, will continue in about an hour or so, if you have time lets keep this conversation open, unless you use gitter? we can chat there

https://gitter.im/

**Comment by gisdev-km** [comment]
Signed up.  Is there a chatroom for this rep?
